# -*- coding: utf-8 -*-
"""FOOD DELIVERY SYSTEM ANALYSIS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14qsYF_HV_Hw7qowcP0n3_-9S1ehkj6_1
"""

# FOOD DELIVERY SYSTEM ANALYSIS – CASSINO
# University Project – Data Analysis with Python


# Install libraries
!pip install pandas matplotlib seaborn -q

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from google.colab import files
import warnings
warnings.filterwarnings("ignore")

# ---------------------------------------
# 1. Upload CSV files
# ---------------------------------------

print("Upload the following files:")
print("- orders.csv")
print("- restaurants.csv")
print("- deliveries.csv")
print("- drivers.csv")

uploaded = files.upload()

required = ['orders.csv', 'restaurants.csv', 'deliveries.csv', 'drivers.csv']


print("All files uploaded correctly.")

# ---------------------------------------
# 2. Load and prepare data
# ---------------------------------------

orders = pd.read_csv("orders.csv")
restaurants = pd.read_csv("restaurants.csv")
deliveries = pd.read_csv("deliveries.csv")
drivers = pd.read_csv("drivers.csv")

# Date handling
orders['order_date'] = pd.to_datetime(orders['order_date'])
orders['month'] = orders['order_date'].dt.to_period("M")
orders['hour'] = orders['order_date'].dt.hour
orders['weekday'] = orders['order_date'].dt.day_name()

# Filter delivered and cancelled orders
delivered = orders[orders['status'] == 'Delivered']
cancelled = orders[orders['status'] == 'Cancelled']

# Basic metrics
total_revenue = delivered['total_amount'].sum()
avg_order_value = delivered['total_amount'].mean()
completion_rate = len(delivered) / len(orders) * 100
cancellation_rate = len(cancelled) / len(orders) * 100

print(f"Total orders: {len(orders)}")
print(f"Delivered orders: {len(delivered)}")
print(f"Total revenue: €{total_revenue:,.2f}")

# ---------------------------------------
# 3. Dashboard
# ---------------------------------------

# The following dashboard provides a visual summary of the main business indicators
sns.set_style("whitegrid")
fig, axes = plt.subplots(3, 2, figsize=(16, 14))
fig.suptitle("Food Delivery System – Cassino", fontsize=18, fontweight="bold")

# 1. Monthly revenue
monthly_revenue = delivered.groupby('month')['total_amount'].sum()
monthly_revenue.index = monthly_revenue.index.astype(str)

axes[0, 0].bar(monthly_revenue.index, monthly_revenue.values)
axes[0, 0].set_title("Monthly Revenue")
axes[0, 0].tick_params(axis='x', rotation=45)

best_month = monthly_revenue.idxmax()

# 2. Order status
orders['status'].value_counts().plot(
    kind='pie', autopct='%1.1f%%', ax=axes[0, 1]
)
axes[0, 1].set_title("Order Status Distribution")
axes[0, 1].set_ylabel("")

# 3. Top restaurants
merged = delivered.merge(restaurants, on="restaurant_id")
top_restaurants = merged.groupby("name")['total_amount'].sum().nlargest(8)

axes[1, 0].barh(top_restaurants.index, top_restaurants.values)
axes[1, 0].set_title("Top Restaurants by Revenue")

# 4. Hourly demand
hourly_orders = delivered.groupby('hour').size()

axes[1, 1].plot(hourly_orders.index, hourly_orders.values, marker='o')
axes[1, 1].set_title("Orders by Hour")

peak_hour = hourly_orders.idxmax()

# 5. Customer segmentation
if 'customer_id' in delivered.columns:
    customer_orders = delivered.groupby('customer_id').size()

    segments = pd.cut(
        customer_orders,
        bins=[0, 1, 2, 4, np.inf],
        labels=['New', 'Occasional', 'Regular', 'VIP']
    )

    segments.value_counts().plot(
        kind='pie', autopct='%1.1f%%', ax=axes[2, 0]
    )
    axes[2, 0].set_title("Customer Segments")
    axes[2, 0].set_ylabel("")

# 6. Delivery ratings
if 'rating' in deliveries.columns:
    deliveries['rating'].value_counts().sort_index().plot(
        kind='bar', ax=axes[2, 1]
    )
    avg_rating = deliveries['rating'].mean()
    axes[2, 1].axhline(avg_rating, linestyle='--')
    axes[2, 1].set_title("Delivery Ratings")

plt.tight_layout()
plt.savefig("food_delivery_dashboard.png", dpi=300)
plt.show()

# ---------------------------------------
# 4. Business metrics summary
# ---------------------------------------

unique_customers = delivered['customer_id'].nunique() if 'customer_id' in delivered else 0
avg_orders_per_customer = len(delivered) / unique_customers if unique_customers > 0 else 0

summary = pd.DataFrame({
    "Metric": [
        "Total Revenue (€)",
        "Average Order Value (€)",
        "Completion Rate (%)",
        "Cancellation Rate (%)",
        "Peak Hour",
        "Best Month",
        "Active Customers",
        "Avg Orders per Customer"
    ],
    "Value": [
        f"{total_revenue:,.2f}",
        f"{avg_order_value:.2f}",
        f"{completion_rate:.1f}",
        f"{cancellation_rate:.1f}",
        f"{peak_hour}:00",
        best_month,
        unique_customers,
        f"{avg_orders_per_customer:.1f}"
    ]
})

summary.to_csv("business_analysis_summary.csv", index=False)
summary.to_csv("key_metrics.csv", index=False)
# ---------------------------------------
# FINAL KEY RESULTS (FOR EXAM / REPORT)
# ---------------------------------------

print("\n" + "="*50)
print("FINAL RESULTS SUMMARY")
print("="*50)

print(f"Total orders: {len(orders)}")
print(f"Delivered orders: {len(delivered)}")
print(f"Total revenue: €{total_revenue:,.2f}")
print(f"Completion rate: {completion_rate:.1f}%")
print(f"Peak hour: {peak_hour}:00")
print(f"Best month: {best_month}")
print(f"Active customers: {unique_customers}")
print(f"Average order value: €{avg_order_value:.2f}")

if 'rating' in deliveries.columns:
    avg_delivery_rating = deliveries['rating'].mean()
    print(f"Average delivery rating: {avg_delivery_rating:.2f}/5")
else:
    print("Average delivery rating: Not available")

print("Analysis completed successfully.")

# ---------------------------------------
# 5. Additional Simple Analysis
# ---------------------------------------

print("\n" + "="*50)
print("ADDITIONAL ANALYSIS FOR REPORT")
print("="*50)

# Orders by weekday
print("\n1. Orders by Weekday:")
weekday_counts = delivered['weekday'].value_counts()
weekday_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
weekday_counts = weekday_counts.reindex(weekday_order, fill_value=0)

for day in weekday_order:
    print(f"  {day}: {weekday_counts[day]} orders")

# Restaurant types
print("\n2. Restaurant Types Performance:")
if 'cuisine_type' in restaurants.columns:
    cuisine_revenue = merged.groupby('cuisine_type')['total_amount'].sum().sort_values(ascending=False)
    for cuisine, revenue in cuisine_revenue.items():
        print(f"  {cuisine}: €{revenue:,.2f}")

# Delivery performance
print("\n3. Delivery Performance:")
if 'rating' in deliveries.columns:
    print(f"  Average rating: {deliveries['rating'].mean():.2f}/5")
    print(f"  5-star deliveries: {deliveries['rating'].value_counts().get(5, 0)}")
    print(f"  1-star deliveries: {deliveries['rating'].value_counts().get(1, 0)}")

# ---------------------------------------
# 6. Extra chart for report
# ---------------------------------------

plt.figure(figsize=(10, 5))

weekday_revenue = delivered.groupby('weekday')['total_amount'].sum()
weekday_revenue = weekday_revenue.reindex(weekday_order, fill_value=0)

plt.bar(weekday_revenue.index, weekday_revenue.values, edgecolor='black')
plt.title("Revenue by Weekday – Cassino Food Delivery")
plt.xlabel("Day of Week")
plt.ylabel("Revenue (€)")
plt.grid(True, alpha=0.3)

for i, v in enumerate(weekday_revenue.values):
    plt.text(i, v + max(weekday_revenue.values)*0.02, f"€{v:,.0f}", ha='center', fontsize=9)

plt.tight_layout()
plt.savefig("weekday_revenue.png", dpi=300)
plt.show()

# ---------------------------------------
# 7. Download results
# ---------------------------------------

files.download("food_delivery_dashboard.png")
files.download("business_analysis_summary.csv")
files.download("key_metrics.csv")
files.download("weekday_revenue.png")